version: 2.1
orbs:
  harden-test-orb: sreejithfocaloid/harden-test-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/


workflows:
  test-deploy:
    jobs:
      - harden-test-orb/instrumentation:
          name: Instrumentation
      - harden-test-orb/hardening:
          name: Hardening
          param1: "${WORKFLOW_ID}"
          requires:
            - harden-test-orb/instrumentation
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: sreejithfocaloid/harden-test-orb
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# VS Code Extension Version: 1.4.0
